heat_template_version: 2015-04-30

description: >
  From webservice
parameters:
  # key_name:
  #   type: string
  #   description: Name of keypair to assign to servers
  image:
    type: string
    description: Name of image to use for servers
  flavor:
    type: string
    description: Flavor to use for servers
  security_groups: 
    type: comma_delimited_list
    description: security group name
  name:
    type: string
    description: Server name
  private_subnet:
    type: string
  

resources:
  server1:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: mmaldoor_key
      networks:
        - port: { get_resource: server_port }

  server_port:
    type: OS::Neutron::Port
    properties:
      network_id: net1
      security_groups: { get_param: security_groups }
      fixed_ips:
        - subnet_id: { get_param: private_subnet }

  server_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: ntnu-internal
      port_id: { get_resource: server_port }


  
# outputs:
#   server1_private_ip:
#     description: IP address of server1 in private network
#     value: { get_attr: [ server1, first_address ] }
#   server1_public_ip:
#     description: Floating IP address of server1 in public network
#     value: { get_attr: [ server1_floating_ip, floating_ip_address ] }
#   server2_private_ip:
#     description: IP address of server2 in private network
#     value: { get_attr: [ server2, first_address ] }
#   server2_public_ip:
#     description: Floating IP address of server2 in public network
#     value: { get_attr: [ server2_floating_ip, floating_ip_address ] }